spring:
  application:
    name: onedollarbid
  datasource:
    url: jdbc:postgresql://postgres:5432/onedollarbid
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

udp:
  multicast:
    address: 230.0.0.0
    port: 5000

server:
  host: localhost
  port: 8080

node:
  id: 1

logging:
  level:
    root: INFO
    onedollarbid: DEBUG
    onedollarbid.udp.RaftLeaderElectionService: DEBUG

manager:
  server:
    host: ${MANAGER_HOST:localhost}
    port: 9090
    protocol: http
    base-url: ${manager.server.protocol}://${manager.server.host}:${manager.server.port}
