services:
  node1:
    container_name: node1
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/onedollarbid
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SERVER_PORT=8080
      - NODE_ID=1
      - MANAGER_SERVER_HOST=host.docker.internal
    depends_on:
      db:
        condition: service_healthy
